// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK0hUtTVjPJD0BJnnevbdZf4GA1tLPKqs',
    appId: '1:418095190519:web:e96374a7991572f2161ef2',
    messagingSenderId: '418095190519',
    projectId: 'doglife-6acad',
    authDomain: 'doglife-6acad.firebaseapp.com',
    databaseURL: 'https://doglife-6acad-default-rtdb.firebaseio.com',
    storageBucket: 'doglife-6acad.firebasestorage.app',
    measurementId: 'G-YSNNP2MTTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzFxJhZqauHCj9l1nOsMnOb9xScpxMB-E',
    appId: '1:418095190519:android:c9c49c8b99c8c98b161ef2',
    messagingSenderId: '418095190519',
    projectId: 'doglife-6acad',
    databaseURL: 'https://doglife-6acad-default-rtdb.firebaseio.com',
    storageBucket: 'doglife-6acad.firebasestorage.app',
  );
}
